import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QTextEdit, QFileDialog, QMessageBox
from PyQt5.QtGui import QIcon, QColor
from PyQt5.QtCore import Qt
import autopep8

class CodeEditor(QMainWindow):
    def __init__(self):
        super().__init__()

        self.initUI()

    def initUI(self):
        self.setWindowTitle("Yazılım Düzenleyici")
        self.setGeometry(100, 100, 800, 600)
        self.setWindowIcon(QIcon("icon.png"))

        self.text_edit = QTextEdit(self)
        self.text_edit.setFontPointSize(12)
        
        # Renkli arkaplan eklemek için:
        palette = self.text_edit.palette()
        palette.setColor(QTextEdit.Base,QColor("#f0f0f0"))
        
         # Renkli yazı tipi eklemek için:
         font = QFont()
         font.setFamily("Courier New")
         font.setStyleHint(QFont.Monospace)
         font.setFixedPitch(True)

          # Yazı rengini değiştirmek için:
          color = QColor("#000000")

          palette.setColor(QPalette.Text,color)

          # Uygula 
           textedit.setPalette(palette)


        

        
       

       
            
        
        
        
        
        
        
        
        
        
        

      

        

      
  

      
      
     
        
         
          
           
            

         
     

     
   
        
    
      
      
    
    

        
        
        
            
                

               
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                                
                                                                        
                                                                                                                                
                        
                    
                    
                
                
                        
                            

        self.setCentralWidget(self.text_edit)

        self.statusBar().showMessage("Yazılım Düzenleyici Hazır")

        self.createMenuBar()

        self.show()

    def createMenuBar(self):
        menubar = self.menuBar()

        file_menu = menubar.addMenu("Dosya")

        open_action = file_menu.addAction("Aç")
       
          # Aksiyon ikonu ekleme:
           open_icon = QIcon()
           open_icon.addPixmap(QPixmap(":/icons/open.png"),QIcon.Normal,QIcon.On)
          
            # İkonu aksiyona ata:
             open_action.setIcon(open_icon)
            
             
             
        
        
        
         
            
            
                
                    

                             
                      
                          
                               
                                   
                                       
                                           
                                               
                
            
            
            

        
        
        
      
     
        
        

 

           
                   
            
                

               
                   
                       
                           
                    
                           
                               
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                                 
                                                                        
                                                                                                                                
                        
                    
                    
                
                
                        


                   
                
                  
                     
                         
                              
                                   
                                       
                                           
                
            
            
            

        
        
        
      
      
     
   
        
    
      
      
    
    

        
        
        
            
                

               
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                               
                                                                        
                                                                                                                                
                        
                    
                    
                
                
                        


                   
                
                  
                     
                         
                              
                                   
                                       
                                           
                
            
            
            

        
        
        
      
      
    
    
    
     

     
   
        
    
      
      
    
    

        
        
        
            
                

               
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                  
                                                             

                     
      
                      



                       





                         
      
                          




                                  



                                     
      
                                          







                                             
     
                                                  






                                                         
    
                                                          









                                                                   
  
                                                                    








                                                                             
    

                                                                               
  
                                                                                










                                                                                       
 
                                                                                           













                                                                                               
   
                                                                                                











                                                              

    
    



























































                                                             
    
                                                          









                                                                   
  
                                                                    








                                                                             
    

                                                                               
  
                                                                                










                                                                                       
 
                                                                                           













                                                                                               
   
      

                                                         
     
                                                   











                                                            
    
  

       

      



        

         

             

               



                    




                         
    
   

     
